[package]
name = "year2024_day16"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
itertools.workspace = true
chumsky.workspace = true
petgraph.workspace = true
enum-iterator.workspace = true
pathfinding.workspace = true
tinyvec.workspace = true
