[workspace]
members = ["common", "cli", "years/*/day*", "years/*/year"]

[workspace.dependencies]
itertools = "0.12"
chumsky = "0.9.3"
strum = "0.25.0"
strum_macros = "0.25.3"
num = "0.4.1"
common = { path = "common" }

[profile.release]
debug = true
