[package]
name = "year2023_day07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common.workspace = true
itertools.workspace = true
strum.workspace = true
strum_macros.workspace = true
