[workspace]
members = ["common", "cli", "generated", "years/*/day*"]
resolver = "2"

[workspace.dependencies]
itertools = "0.13"
chumsky = "0.9.3"
strum = "0.26.3"
strum_macros = "0.26.4"
num = "0.4.1"
common = { path = "common" }

[profile.release]
debug = true
